AWSTemplateFormatVersion: '2010-09-09'
Parameters:
    DomainNameParametr:
        Type: String
        Description: The DNS name of an existing Amazon Route 53 hosted zone e.g. jevsejev.io
        AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
        ConstraintDescription: must be a valid DNS zone name.
    BucketNameParametr:
        Type: String
        Description: Amazon S3 files bucket name
    HostedZoneIdParametr:
        Type: String
        Description: Amazon Route53 Hosted Zone Id for DomainName
    CertificateArnParametr:
        Type: String
        Description: Certificate Link


Resources:
    Bucket1:
        Type: AWS::S3::Bucket
            Properties: 
                BucketName: !Ref BucketNameParametr
                AccessControl: private
    BucketPolicy1:
        Type: AWS::S3::BucketPolicy
            Properties:
                Bucket: !Ref 'Bucket1'
                PolicyDocument:
                    Statement:
                    - Sid: PublicReadForGetBucketObjects
                    Effect: Allow
                    Principal: '*'
                    Action: s3:GetObject
                    Resource: !Join ['', ['arn:aws:s3:::', !Ref 'Bucket1', /*]]
    Cloudfront1:
        Type: AWS::CloudFront::Distribution
        DependsOn:
            - Bucket1
        Properties:
            DistributionConfig:
            Comment: Cloudfront Distribution pointing to S3 bucket
            Origins:
            - DomainName: !Select [2, !Split ["/", !GetAtt Bucket1.WebsiteURL]]
            Id: S3Origin
            CustomOriginConfig:
                HTTPSPort: '443'
                OriginProtocolPolicy: https-only
            Enabled: true
            HttpVersion: 'http2'
            ViewerCertificate:
                AcmCertificateArn: !Ref CertificateArnParametr
                SslSupportMethod: sni-only
    DNS:
        Type: AWS::Route53::HostedZone
        Properties:
            HostedZoneConfig:
                HostedZoneId: !Ref HostedZoneIdParametr 
                Comment: !Join ['', ['Hosted zone for ', !Ref 'DomainNameParametr']]
        Name: !Ref 'DomainNameParametr'
        HostedZoneTags:
            - Key: Application
            Value: Blog

Outputs:
  CloudfrontId:
    Value: !Ref Cloudfront1
    Description: Cloudfront Id
  